CREATE TABLE IF NOT EXISTS user
(
    ID VARCHAR PRIMARY KEY NOT NULL,
    Username VARCHAR UNIQUE NOT NULL,
    PasswordHash VARCHAR NOT NULL
);

CREATE INDEX IF NOT EXISTS user_username
ON user (Username);